---
title: 'Reproducible Research: Peer Assessment 1'
output:
  html_document:
    keep_md: yes
  pdf_document: default
---


## Loading and preprocessing the data

```{r}
unzip("activity.zip")
activity<-read.csv("activity.csv")
activity<-activity[!is.na(activity$steps),]
```


## What is mean total number of steps taken per day?
```{r}
library(dplyr)
library(ggplot2)
library(timeDate)
total_steps_per_day=activity%>%group_by(date)%>%summarise(total_steps=sum(steps))
gg=ggplot(total_steps_per_day,aes(x=total_steps))
gg+geom_histogram(colour="black", fill="white")+labs(title="histogram of total steps per day",x="total stpes per day")
mean_total_steps_per_day=mean(total_steps_per_day$total_steps)
print(mean_total_steps_per_day)
median_total_steps_per_day=median(total_steps_per_day$total_steps)
print(median_total_steps_per_day)

```

## What is the average daily activity pattern?
```{r}
mean_steps_per_interval=activity%>%group_by(interval)%>%summarise(mean_steps_per_interval=mean(steps))
g<-ggplot(mean_steps_per_interval,aes(x=interval,y=mean_steps_per_interval))
g+geom_line()
ordered<-mean_steps_per_interval%>%arrange(desc(mean_steps_per_interval))
ordered$interval[1]
```



## Imputing missing values
```{r}
activity_na<-read.csv("activity.csv")
row_is_na<-apply(activity_na, 1, function(x) any(is.na(x)))
print(sum(row_is_na))
activity_new<-activity_na %>% group_by(interval) %>% mutate(steps = ifelse(is.na(steps),mean(steps,na.rm=T), steps))
total_steps_per_day=activity_new%>%group_by(date)%>%summarise(total_steps=sum(steps))
gg=ggplot(total_steps_per_day,aes(x=total_steps))
gg+geom_histogram(colour="black", fill="white")+labs(title="histogram of total steps per day",x="total stpes per day")
mean_total_steps_per_day=mean(total_steps_per_day$total_steps)
print(mean_total_steps_per_day)
median_total_steps_per_day=median(total_steps_per_day$total_steps)
print(median_total_steps_per_day)

```



## Are there differences in activity patterns between weekdays and weekends?
```{r}
activity_new_wkd<-activity_new%>%mutate(wkd=ifelse(isWeekend(date),"weekend","weekday"))
activity_new_wkd$wkd<-factor(activity_new_wkd$wkd)
activity_wkd_weekday=activity_new_wkd%>%group_by(wkd,interval)%>%summarise(mean_steps_per_interval=mean(steps))
g<-ggplot(activity_wkd_weekday,aes(x=interval,y=mean_steps_per_interval))
g+geom_line(col="blue")+facet_wrap(~wkd,ncol=1)+theme_bw()
```

